--문자열함수
--LOWER(), INITCAP(), UPPER()
SELECT LOWER('HELLO'), INITCAP('HELLO'), UPPER('HELLO') FROM DUAL; --DUAL은 가상테이블
SELECT LOWER(FIRST_NAME), INITCAP(FIRST_NAME), UPPER(FIRST_NAME) FROM EMPLOYEES;

--함수는 WHERE절에도 적용됩니다.
SELECT FIRST_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'STEVEN';

--LENTH() - 길이, INSTR() - 문자 찾기
SELECT FIRST_NAME, LENGTH(FIRST_NAME), INSTR(FIRST_NAME,'e') FROM EMPLOYEES;

--SUBSTR() - 문자열자르기, CONCAT() - 문자열합치기
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 1, 3) FROM EMPLOYEES; --1번째에서 3글자를 자름
SELECT FIRST_NAME, CONCAT(FIRST_NAME, LAST_NAME), FIRST_NAME || LAST_NAME FROM EMPLOYEES;

--LPAD() - 왼쪽 채우기, RPAD() - 오른쪽 채우기
SELECT LPAD('HELLO', 10, '*') FROM DUAL;
SELECT LPAD(SALARY, 10, '*') FROM EMPLOYEES;
SELECT RPAD('HELLO', 10, '-') FROM DUAL;

--LTRIM() - 왼쪽제거, RTRIM() - 오른쪽제거, TRIM() - 양쪽 제거
SELECT LTRIM('    HELLO') FROM DUAL;
SELECT LTRIM(FIRST_NAME, 'A') FROM EMPLOYEES; --왼쪽에 처음 발견되는 문제 A제거
SELECT RTRIM('    HELLO  ') AS RESULT FROM DUAL;
SELECT TRIM('    HELLO   ') AS RESULT FROM DUAL;

--REPLACE() - 문자열 변경
SELECT REPLACE('HELLO WORLD','HELLO','BYE') FROM DUAL;
SELECT REPLACE('HELLO WORLD ~! ', ' ', '') FROM DUAL; --모든 공백 제거 

--중첩
SELECT REPLACE( REPLACE('HELLO WORLD ~!;', 'HELLO', 'BYE'), ' ', '') FROM DUAL;




