--그룹함수 : 여러행에 대하여 집계출력
--AVG, SUM, MIN, MAX, COUNT
SELECT AVG(SALARY), SUM(SALARY), MIN(SALARY), MAX(SALARY), COUNT(SALARY) FROM EMPLOYEES;
SELECT MIN(HIRE_DATE), MAX(HIRE_DATE) FROM EMPLOYEES;
SELECT MIN(FIRST_NAME), MAX(FIRST_NAME) FROM EMPLOYEES;
-- => 여러 해에 대한 집계


--COUNT (컬럼) :  NULL이 아닌 데이터 개수
--COUNT(*) : 전체 행의 개수
SELECT COUNT(FIRST_NAME) FROM EMPLOYEES;
SELECT COUNT(DEPARTMENT_ID) FROM EMPLOYEES;
--(두 행을 조회해보니 행 개수가 차이가 난다.
SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES;
NULL값이 아닌 실제로 가진 숫자값들이기 때문에...?
SELECT COUNT(*) FROM EMPLOYEES;


--그룹함수: 그룹함수와 일반컬럼을 동시에 출력할 수 없다.(오라클만)
SELECT FIRST_NAME, SUM(SALARY) FROM EMPLOYEES;




